#ifndef USER_INPUT_READER_HEADER
#define USER_INPUT_READER_HEADER

enum UserInput {
  USER_INPUT_START_SESSION,
  USER_INPUT_FORCE_STOP_SESSION,
  USER_INPUT_DISPLAY_NUMBER_OF_SESSIONS,
  USER_INPUT_RESET_SESSION_COUNTER,
  USER_INPUT_TURN_OFF_DISPLAY_SCREEN,
  USER_INPUT_NOTHING
};

class UserInputReader {
public:
  virtual void Initialize() = 0;
  virtual UserInput ReadUserInput() const = 0;
};

#endif